#!/bin/bash

## Copyright ©UDPTeam

## Discord: https://discord.gg/civ3

## Script to keep-alive your DNSTT server domain record query from target resolver/local dns server

## Run this script excluded to your VPN tunnel (split vpn tunneling mode)

## run command: ./globe-experiment.sh l



## Your DNSTT Nameserver & your Domain `A` Record

NS='xp1.wampipti.net'
NS1='xp2.wampipti.net'
NS2='xp3.wampipti.net'
NS3='xp4.wampipti.net'
NS4='xp5.wampipti.net'
NS5='xp6.wampipti.net'
A='wampipti.net'

## Repeat dig cmd loop time (seconds) (positive interger only)

LOOP_DELAY=5



## Add your DNS here

declare -a HOSTS=('124.6.181.4'124.6.181.20'112.198.115.44'112.198.126.116'124.6.181.36'124.6.181.12'124.6.181.12'124.6.181.25'112.198.115.60'121.54.70.170'121.54.70.150'10.0.0.1'10.0.0.0'192.53.172.50'124.40.228.1'103.86.50.133'49.0.72.60'124.40.229.69'124.40.228.1'10.17.160.102'103.242.23.166'202.134.14.230'123.108.240.174'125.5.210.212'125.5.210.213'10.86.65.154'10.86.65.155'10.86.65.156'10.86.65.157'10.86.65.158'121.54.70.130'121.54.70.131'121.54.70.134'121.54.70.138'121.54.70.139'121.54.70.141'121.54.70.142'121.54.70.146'121.54.70.148'121.54.70.149'121.54.70.150'121.54.70.155'121.54.70.156'121.54.70.157'121.54.70.158'121.54.70.163'121.54.70.164'121.54.70.165'121.54.70.166'121.54.70.163'121.54.70.163'124.6.181.4'124.6.181.12'124.6.181.25'124.6.181.26'124.6.181.27'124.6.181.28'124.6.181.36'112.198.115.36'112.198.115.44')



## Linux' dig command executable filepath

## Select value: "CUSTOM|C" or "DEFAULT|D"

DIG_EXEC="DEFAULT"

## if set to CUSTOM, enter your custom dig executable path here

CUSTOM_DIG=/data/data/com.termux/files/home/go/bin/fastdig



######################################

######################################

######################################

######################################

######################################

VER=0.1

case "${DIG_EXEC}" in

 DEFAULT|D)

 _DIG="$(command -v dig)"

 ;;

 CUSTOM|C)

 _DIG="${CUSTOM_DIG}"

 ;;

esac

if [ ! $(command -v ${_DIG}) ]; then

 printf "%b" "Dig command failed to run, " \

 "please install dig(dnsutils) or check " \

 "\$DIG_EXEC & \$CUSTOM_DIG variable inside $( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )/$(basename "$0") file.\n" && exit 1

fi

endscript() {

 unset NS NS1 NS2 NS3 NS4 NS5 A LOOP_DELAY HOSTS _DIG DIG_EXEC CUSTOM_DIG T R M

 exit 1

}

trap endscript 2 15

check(){

 for ((i=0; i<"${#HOSTS[*]}"; i++)); do

  for R in "${A}" "${NS}" "${NS1}" "${NS2}" "${NS3}" "${NS4}" "${NS5}"; do

   T="${HOSTS[$i]}"
   [[ -z $(timeout -k 3 3 ${_DIG} @${T} ${R}) ]] && M=31 || M=32;
   echo -e "\e[1;${M}m\$ R:${R} D:${T}\e[0m"
   unset T R M
  done
 done
}


echo "DNSTT Keep-Alive script <Discord @civ3>"

echo -e "DNS List: [\e[1;34m${HOSTS[*]}\e[0m]"

echo "CTRL + C to close script"

[[ "${LOOP_DELAY}" -eq 1 ]] && let "LOOP_DELAY++";

case "${@}" in

 loop|l)

 echo "Script loop: ${LOOP_DELAY} seconds"

 while true; do

  check

  echo '.--. .-.. . .- ... .     .-- .- .. -'

  sleep ${LOOP_DELAY}

 done

 ;;

 *)

 check

 ;;

esac

exit 0
